/* Contas a pagar — total pendente com vencimento hoje. @EMPRESA parametrizado. */
SELECT SUM(CP.TOTAL) AS "value", 'ion-cash' AS "icon"
FROM CONTA_PARCELA CP
JOIN CONTA C        ON C.CODIGOCONTA       = CP.CODIGOCONTA
JOIN PESSOA P       ON P.CODIGOPESSOA      = C.CODIGOPESSOA
JOIN PESSOA_TIPO PT ON PT.CODIGOTIPO       = P.CODIGOTIPO
JOIN CAIXA CX       ON CX.CODIGOLANCAMENTO = C.CODIGOLANCAMENTO
JOIN USUARIO U      ON U.CODIGOUSUARIO     = CX.CODIGOUSUARIO
WHERE CP.TOTAL > 0
  AND UPPER(CP.SITUACAO) = 'PENDENTE'
  AND CP.CODIGO_CONTA_CHEQUE IS NULL
  AND CP.DATAVENCIMENTO >= @INI_HOJE
  AND CP.DATAVENCIMENTO <  @FIM_HOJE
  AND U.CODIGOEMPRESA = @EMPRESA
  AND (PT.CODIGOTIPO = 3 OR PT.CODIGOTIPO = 4)
