/* Top 8 fornecedores/credores com vencimento nos proximos 7 dias. Tipo ranking. */
SELECT FIRST 8
    P.NOME          AS "label",
    SUM(CP.TOTAL)   AS "value"
FROM CONTA_PARCELA CP
JOIN CONTA C        ON C.CODIGOCONTA       = CP.CODIGOCONTA
JOIN PESSOA P       ON P.CODIGOPESSOA      = C.CODIGOPESSOA
JOIN PESSOA_TIPO PT ON PT.CODIGOTIPO       = P.CODIGOTIPO
JOIN CAIXA CX       ON CX.CODIGOLANCAMENTO = C.CODIGOLANCAMENTO
JOIN USUARIO U      ON U.CODIGOUSUARIO     = CX.CODIGOUSUARIO
WHERE CP.TOTAL > 0
  AND UPPER(CP.SITUACAO) = 'PENDENTE'
  AND CP.CODIGO_CONTA_CHEQUE IS NULL
  AND CP.DATAVENCIMENTO >= @INI_HOJE
  AND CP.DATAVENCIMENTO <  DATEADD(7 DAY TO @INI_HOJE)
  AND U.CODIGOEMPRESA = @EMPRESA
  AND (PT.CODIGOTIPO = 3 OR PT.CODIGOTIPO = 4)
GROUP BY P.CODIGOPESSOA, P.NOME
ORDER BY SUM(CP.TOTAL) DESC
