// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SigeDash.Api.Data;

#nullable disable

namespace SigeDash.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810211459_AddLimiteDispositivos")]
    partial class AddLimiteDispositivos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SigeDash.Api.Modelos.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ChaveApi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LimiteDispositivos")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChaveApi")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SigeDash.Api.Modelos.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoEmpresa")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("SigeDash.Api.Modelos.Snapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoEmpresa")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndicadorHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecebidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "CodigoEmpresa", "IndicadorHandle", "GeradoEm");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("SigeDash.Api.Modelos.UsuarioApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeExibicao")
                        .HasColumnType("text");

                    b.Property<bool>("PrecisaTrocarSenha")
                        .HasColumnType("boolean");

                    b.Property<string>("SecoesPermitidas")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessaoToken")
                        .HasColumnType("text");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("integer");

                    b.Property<bool>("TotpAtivado")
                        .HasColumnType("boolean");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Login")
                        .IsUnique();

                    b.ToTable("UsuariosApp");
                });

            modelBuilder.Entity("SigeDash.Api.Modelos.Loja", b =>
                {
                    b.HasOne("SigeDash.Api.Modelos.Cliente", null)
                        .WithMany("Lojas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SigeDash.Api.Modelos.Cliente", b =>
                {
                    b.Navigation("Lojas");
                });
#pragma warning restore 612, 618
        }
    }
}
