/* Produtos com estoque abaixo do minimo. @EMPRESA parametrizado. */
SELECT FIRST 10
       PB.NOME AS "label",
       PE.ESTOQUE AS "value",
       PB.ESTOQUEMINIMO AS "minimo"
FROM PRODUTO_BASE PB
JOIN PRODUTO P         ON PB.CODIGOBASEPRODUTO = P.CODIGOBASEPRODUTO
JOIN PRODUTO_ESTOQUE PE ON P.CODIGOPRODUTO = PE.CODIGOPRODUTO
WHERE PE.CODIGOEMPRESA = @EMPRESA
  AND PE.ESTOQUE < PB.ESTOQUEMINIMO
  AND P.DESATIVADO = 'N'
ORDER BY PE.ESTOQUE ASC
