/* Top 8 formas de pagamento por valor vendido no mes. Tipo ranking. */
SELECT FIRST 8
    COALESCE(FP.DESCRICAO, 'Não informado') AS "label",
    SUM(CP.TOTAL)                           AS "value"
FROM PEDIDO P
JOIN CAIXA CX               ON CX.CODIGOLANCAMENTO   = P.CODIGOLANCAMENTO
JOIN PESSOA PESS             ON PESS.CODIGOPESSOA     = P.CODIGOPESSOA
JOIN CONTA C                ON C.CODIGOLANCAMENTO     = P.CODIGOLANCAMENTO
JOIN CONTA_PARCELA CP       ON CP.CODIGOCONTA         = C.CODIGOCONTA
LEFT JOIN FORMA_PAGAMENTO_CONDICAO FPC
                            ON FPC.CODIGO_FORMA_PAGAMENTO_CONDICAO = CP.CODIGO_FORMA_PAGAMENTO_CONDICAO
LEFT JOIN FORMA_PAGAMENTO FP ON FP.CODIGO_FORMA_PAGAMENTO = FPC.CODIGO_FORMA_PAGAMENTO
WHERE P.CODIGOEMPRESA = @EMPRESA
  AND (P.CODIGO_PEDIDO_TIPO NOT IN (4, 8) OR P.CODIGO_PEDIDO_TIPO IS NULL)
  AND P.CODIGO_PEDIDO_SITUACAO = 2
  AND P.CODIGOLANCAMENTO IS NOT NULL
  AND PESS.CODIGOTIPO = 1
  AND CX.DATAHORALANCAMENTO >= @INI_MES
  AND CX.DATAHORALANCAMENTO <  @FIM_MES
GROUP BY FP.CODIGO_FORMA_PAGAMENTO, FP.DESCRICAO
ORDER BY SUM(CP.TOTAL) DESC
