/* Analise de pico de vendas por hora do dia de hoje.
   Retorna: hora (ex: 08h) e quantidade de pedidos. @EMPRESA parametrizado. */
SELECT
    LPAD(EXTRACT(HOUR FROM CX.DATAHORALANCAMENTO), 2, '0') || 'h' AS "bar",
    COUNT(*) AS "value"
FROM PEDIDO P
JOIN PESSOA PESS ON PESS.CODIGOPESSOA = P.CODIGOPESSOA
JOIN CAIXA CX    ON CX.CODIGOLANCAMENTO = P.CODIGOLANCAMENTO
WHERE P.CODIGOEMPRESA = @EMPRESA
  AND (P.CODIGO_PEDIDO_TIPO NOT IN (4, 8) OR P.CODIGO_PEDIDO_TIPO IS NULL)
  AND P.CODIGO_PEDIDO_SITUACAO <> 4
  AND P.CODIGOLANCAMENTO IS NOT NULL
  AND PESS.CODIGOTIPO = 1
  AND CX.DATAHORALANCAMENTO >= @INI_HOJE
  AND CX.DATAHORALANCAMENTO <  @FIM_HOJE
GROUP BY EXTRACT(HOUR FROM CX.DATAHORALANCAMENTO)
ORDER BY EXTRACT(HOUR FROM CX.DATAHORALANCAMENTO)
