/* Quantidade de pedidos realizados hoje. formato = qtd (nao monetario). */
SELECT
    COUNT(*)  AS "value",
    'qtd'     AS "formato"
FROM PEDIDO P
JOIN CAIXA CX    ON CX.CODIGOLANCAMENTO = P.CODIGOLANCAMENTO
JOIN PESSOA PESS ON PESS.CODIGOPESSOA   = P.CODIGOPESSOA
WHERE P.CODIGOEMPRESA = @EMPRESA
  AND (P.CODIGO_PEDIDO_TIPO NOT IN (4, 8) OR P.CODIGO_PEDIDO_TIPO IS NULL)
  AND P.CODIGO_PEDIDO_SITUACAO <> 4
  AND P.CODIGOLANCAMENTO IS NOT NULL
  AND PESS.CODIGOTIPO = 1
  AND CX.DATAHORALANCAMENTO >= @INI_HOJE
  AND CX.DATAHORALANCAMENTO <  @FIM_HOJE
