/* Ticket medio por pedido no dia de hoje. sub = quantidade de pedidos. */
SELECT
    SUM(P.VALORTOTAL) / NULLIF(COUNT(*), 0)             AS "value",
    CAST(COUNT(*) AS VARCHAR(20)) || ' pedidos hoje'    AS "sub"
FROM PEDIDO P
JOIN CAIXA CX    ON CX.CODIGOLANCAMENTO = P.CODIGOLANCAMENTO
JOIN PESSOA PESS ON PESS.CODIGOPESSOA   = P.CODIGOPESSOA
WHERE P.CODIGOEMPRESA = @EMPRESA
  AND (P.CODIGO_PEDIDO_TIPO NOT IN (4, 8) OR P.CODIGO_PEDIDO_TIPO IS NULL)
  AND P.CODIGO_PEDIDO_SITUACAO <> 4
  AND P.CODIGOLANCAMENTO IS NOT NULL
  AND PESS.CODIGOTIPO = 1
  AND CX.DATAHORALANCAMENTO >= @INI_HOJE
  AND CX.DATAHORALANCAMENTO <  @FIM_HOJE
