/* Top 5 clientes que mais compraram no mes. Paridade PlugBot.
   @EMPRESA e datas SARGAVEIS parametrizados. */
SELECT FIRST 5
    CLIENTE.NOME      AS "label",
    SUM(P.VALORTOTAL) AS "value"
FROM PEDIDO P
JOIN CAIXA CX               ON CX.CODIGOLANCAMENTO = P.CODIGOLANCAMENTO
JOIN PESSOA CLIENTE          ON CLIENTE.CODIGOPESSOA = P.CODIGOPESSOA
LEFT JOIN PESSOA_FUNCIONARIO FUNC ON FUNC.CODIGOPESSOA = P.CODIGOFUNCIONARIO
WHERE P.CODIGO_PEDIDO_SITUACAO = 2
  AND P.CODIGOEMPRESA = @EMPRESA
  AND CX.DATAHORALANCAMENTO >= @INI_MES
  AND CX.DATAHORALANCAMENTO <  @FIM_MES
GROUP BY CLIENTE.CODIGOPESSOA, CLIENTE.NOME
ORDER BY SUM(P.VALORTOTAL) DESC
