/* Top 5 produtos mais vendidos no mes corrente (paridade PlugBot).
   Reescrito por nos: @EMPRESA parametrizado + datas SARGAVEIS (>= @INI_MES AND < @FIM_MES),
   no lugar das subqueries com extract(day...) do original.
   Rankeia por valor vendido, igual ao SigeDash atual (Codigo_Pedido_Situacao = 2). */
SELECT FIRST 5
       CASE WHEN PR.NOME_COMPLETO IS NULL THEN PB.NOME ELSE PR.NOME_COMPLETO END AS "label",
       SUM(PP.VALORTOTAL) AS "value"
FROM PEDIDO P
JOIN PEDIDO_PRODUTO PP ON PP.CODIGOPEDIDO = P.CODIGOPEDIDO
JOIN CAIXA CX          ON CX.CODIGOLANCAMENTO = P.CODIGOLANCAMENTO
JOIN PRODUTO PR        ON PR.CODIGOPRODUTO = PP.CODIGOPRODUTO
JOIN PRODUTO_BASE PB   ON PB.CODIGOBASEPRODUTO = PR.CODIGOBASEPRODUTO
WHERE P.CODIGOEMPRESA = @EMPRESA
  AND P.CODIGO_PEDIDO_SITUACAO = 2
  AND CX.DATAHORALANCAMENTO >= @INI_MES
  AND CX.DATAHORALANCAMENTO <  @FIM_MES
GROUP BY PP.CODIGOPRODUTO, PB.NOME, PR.NOME_COMPLETO
ORDER BY SUM(PP.VALORTOTAL) DESC
