/* Total de vendas acumulado no mes corrente. Paridade PlugBot.
   Datas SARGAVEIS: >= @INI_MES AND < @FIM_MES. @EMPRESA parametrizado. */
SELECT SUM(P.VALORTOTAL) AS "value", 'ion-calculator' AS "icon"
FROM PEDIDO P
JOIN PESSOA PESS ON PESS.CODIGOPESSOA = P.CODIGOPESSOA
JOIN CAIXA CX    ON CX.CODIGOLANCAMENTO = P.CODIGOLANCAMENTO
WHERE P.CODIGOEMPRESA = @EMPRESA
  AND (P.CODIGO_PEDIDO_TIPO NOT IN (4, 8) OR P.CODIGO_PEDIDO_TIPO IS NULL)
  AND P.CODIGO_PEDIDO_SITUACAO <> 4
  AND P.CODIGOLANCAMENTO IS NOT NULL
  AND PESS.CODIGOTIPO = 1
  AND CX.DATAHORALANCAMENTO >= @INI_MES
  AND CX.DATAHORALANCAMENTO <  @FIM_MES
