/* Fase 1 - paridade. Reescrito por nos:
   - @EMPRESA parametrizado (era literal 1)
   - filtro de data SARGAVEL: CX.DATAHORALANCAMENTO >= @INI_HOJE AND < @FIM_HOJE
     (o original usava cast(... as date) = current_date, que anula indice por data) */
SELECT SUM(P.VALORTOTAL) AS "value", 'ion-calculator' AS "icon"
FROM PEDIDO P
JOIN PESSOA PESS ON PESS.CODIGOPESSOA = P.CODIGOPESSOA
JOIN CAIXA CX    ON CX.CODIGOLANCAMENTO = P.CODIGOLANCAMENTO
WHERE P.CODIGOEMPRESA = @EMPRESA
  AND (P.CODIGO_PEDIDO_TIPO NOT IN (4, 8) OR P.CODIGO_PEDIDO_TIPO IS NULL)
  AND P.CODIGO_PEDIDO_SITUACAO <> 4
  AND P.CODIGOLANCAMENTO IS NOT NULL
  AND PESS.CODIGOTIPO = 1
  AND CX.DATAHORALANCAMENTO >= @INI_HOJE
  AND CX.DATAHORALANCAMENTO <  @FIM_HOJE
