// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SigeDash.Central.Data;

#nullable disable

namespace SigeDash.Central.Migrations
{
    [DbContext(typeof(CentralDbContext))]
    partial class CentralDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SigeDash.Central.Modelos.ClienteCentral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ChaveTelemetria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LimiteDispositivos")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChaveTelemetria")
                        .IsUnique();

                    b.HasIndex("Nome");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SigeDash.Central.Modelos.Heartbeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<int>("LimiteDispositivos")
                        .HasColumnType("integer");

                    b.Property<string>("Os")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecebidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusBackend")
                        .HasColumnType("text");

                    b.Property<string>("StatusPg")
                        .HasColumnType("text");

                    b.Property<long>("UptimeSeg")
                        .HasColumnType("bigint");

                    b.Property<int>("UsuariosAtivos")
                        .HasColumnType("integer");

                    b.Property<string>("Versao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Heartbeats");
                });

            modelBuilder.Entity("SigeDash.Central.Modelos.HeartbeatHistorico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuariosAtivos")
                        .HasColumnType("integer");

                    b.Property<string>("Versao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Ts");

                    b.ToTable("HeartbeatHistorico");
                });

            modelBuilder.Entity("SigeDash.Central.Modelos.IndicadorSaude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mensagem")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoErro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoSucesso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Handle")
                        .IsUnique();

                    b.ToTable("IndicadoresSaude");
                });

            modelBuilder.Entity("SigeDash.Central.Modelos.UsuarioPainel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("UsuariosPainel");
                });

            modelBuilder.Entity("SigeDash.Central.Modelos.Heartbeat", b =>
                {
                    b.HasOne("SigeDash.Central.Modelos.ClienteCentral", null)
                        .WithOne("Heartbeat")
                        .HasForeignKey("SigeDash.Central.Modelos.Heartbeat", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SigeDash.Central.Modelos.IndicadorSaude", b =>
                {
                    b.HasOne("SigeDash.Central.Modelos.ClienteCentral", null)
                        .WithMany("Indicadores")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SigeDash.Central.Modelos.ClienteCentral", b =>
                {
                    b.Navigation("Heartbeat");

                    b.Navigation("Indicadores");
                });
#pragma warning restore 612, 618
        }
    }
}
