/* Saldo bancario consolidado: conta corrente + cartao + cheque compensado.
   UNION de 3 sub-queries, agrupado por banco. @EMPRESA parametrizado.

   IMPORTANTE: o SELECT DISTINCT de cada sub-query precisa manter as colunas
   P.NOME, P.CODIGOPESSOA, PT.CODIGOTIPO (e CCAP.* / CCH.* no cartao/cheque).
   Elas fazem parte da chave de deduplicacao do Sigecom - remover qualquer uma
   distorce os valores (ex: BANCO DO BRASIL passou a mostrar -15596 em vez de -648).
   Fonte canonica: SQLs-PlugBot/plugdash_saldodiario. */
SELECT
    TESTE.NOMEBANCO    AS "nome",
    'Conta Bancária'   AS "descricao",
    'Saldo disponível' AS "info",
    SUM(TESTE."valor") AS "valor"
FROM (

    /* 1 — Transferencias bancarias diretas */
    SELECT
        BANCO.CODIGOCONTABANCO,
        BANCO.NOMEBANCO,
        SUM(CASE WHEN BANCO.OPERACAO = 'C' THEN BANCO.VALOR ELSE 0 END)
      - SUM(CASE WHEN BANCO.OPERACAO = 'D' THEN BANCO.VALOR ELSE 0 END) AS "valor"
    FROM (
        SELECT DISTINCT
            CB.CODIGOBAIXA,
            P.NOME,
            P.CODIGOPESSOA,
            PT.CODIGOTIPO,
            CCP.OPERACAO_PLANO_CONTA AS OPERACAO,
            CNTB.NOME                AS NOMEBANCO,
            CBCB.VALOR,
            CNTB.CODIGOCONTABANCO
        FROM CONTA_BAIXA CB
        JOIN CONTA_BAIXA_CONTA_PARCELA CBCP ON CB.CODIGOBAIXA     = CBCP.CODIGOBAIXA
        JOIN CONTA_PARCELA CPAR             ON CPAR.CODIGOPARCELA   = CBCP.CODIGOPARCELA
        JOIN CONTA C                        ON C.CODIGOCONTA        = CPAR.CODIGOCONTA
        JOIN PESSOA P                       ON P.CODIGOPESSOA       = C.CODIGOPESSOA
        JOIN PESSOA_TIPO PT                 ON P.CODIGOTIPO         = PT.CODIGOTIPO
        JOIN CAIXA_CONTA_PLANO CCP          ON C.CODIGOPLANOCONTA   = CCP.CODIGOPLANOCONTA
        JOIN CAIXA CX                       ON C.CODIGOLANCAMENTO   = CX.CODIGOLANCAMENTO
        JOIN CAIXA_ABERTURA CA              ON CX.CODIGOABERTURA    = CA.CODIGOABERTURA
        JOIN CAIXA_CONFIG CXC               ON CA.CODIGOCAIXA       = CXC.CODIGOCAIXA
        JOIN CONTA_BAIXA_CONTA_BANCO CBCB   ON CB.CODIGOBAIXA       = CBCB.CODIGOBAIXA
        JOIN CONTA_BANCO CNTB               ON CBCB.CODIGOCONTABANCO = CNTB.CODIGOCONTABANCO
        WHERE CXC.CODIGOEMPRESA = @EMPRESA
          AND CBCB.DATACOMPENSACAO IS NOT NULL
          AND CNTB.DESATIVADO = 'N'
    ) AS BANCO
    GROUP BY BANCO.NOMEBANCO, BANCO.CODIGOCONTABANCO

    UNION ALL

    /* 2 — Cartao de credito/debito compensado */
    SELECT
        BANCOCARTAO.CODIGOCONTABANCOSUB,
        BANCOCARTAO.NOMEBANCO,
        SUM(CASE WHEN BANCOCARTAO.OPERACAO = 'C' THEN BANCOCARTAO.VALOR ELSE 0 END)
      - SUM(CASE WHEN BANCOCARTAO.OPERACAO = 'D' THEN BANCOCARTAO.VALOR ELSE 0 END) AS "valor"
    FROM (
        SELECT DISTINCT
            CB.CODIGOBAIXA,
            P.NOME,
            P.CODIGOPESSOA,
            PT.CODIGOTIPO,
            CCP.OPERACAO_PLANO_CONTA    AS OPERACAO,
            CCA.TITULAR,
            CCA.NSU,
            CCAP.*,
            CCAP.CODIGOCONTABANCO       AS CODIGOCONTABANCOSUB,
            CNTB.NOME                   AS NOMEBANCO
        FROM CONTA_BAIXA CB
        JOIN CONTA_BAIXA_CONTA_PARCELA CBCP ON CB.CODIGOBAIXA     = CBCP.CODIGOBAIXA
        JOIN CONTA_PARCELA CPAR             ON CPAR.CODIGOPARCELA   = CBCP.CODIGOPARCELA
        JOIN CONTA C                        ON C.CODIGOCONTA        = CPAR.CODIGOCONTA
        JOIN PESSOA P                       ON P.CODIGOPESSOA       = C.CODIGOPESSOA
        JOIN PESSOA_TIPO PT                 ON P.CODIGOTIPO         = PT.CODIGOTIPO
        JOIN CAIXA_CONTA_PLANO CCP          ON CPAR.CODIGO_PLANO_CONTA = CCP.CODIGOPLANOCONTA
        JOIN CAIXA CX                       ON C.CODIGOLANCAMENTO   = CX.CODIGOLANCAMENTO
        JOIN CAIXA_ABERTURA CA              ON CX.CODIGOABERTURA    = CA.CODIGOABERTURA
        JOIN CAIXA_CONFIG CXC               ON CA.CODIGOCAIXA       = CXC.CODIGOCAIXA
        JOIN CONTA_BAIXA_CONTA_CARTAO CBCCA ON CB.CODIGOBAIXA       = CBCCA.CODIGOBAIXA
        JOIN CONTA_CARTAO CCA               ON CBCCA.CODIGOCARTAO   = CCA.CODIGOCARTAO
        JOIN CONTA_CARTAO_PARCELA CCAP      ON CCA.CODIGOCARTAO     = CCAP.CODIGOCARTAO
        JOIN CONTA_BANCO CNTB               ON CCAP.CODIGOCONTABANCO = CNTB.CODIGOCONTABANCO
        WHERE CCAP.DATACOMPENSACAO IS NOT NULL
          AND CNTB.DESATIVADO = 'N'
    ) AS BANCOCARTAO
    GROUP BY BANCOCARTAO.NOMEBANCO, BANCOCARTAO.CODIGOCONTABANCOSUB

    UNION ALL

    /* 3 — Cheques compensados */
    SELECT
        BANCOCHEQUE.CODIGOCONTABANCOSUB,
        BANCOCHEQUE.NOMEBANCO,
        SUM(CASE WHEN BANCOCHEQUE.OPERACAO = 'C' THEN BANCOCHEQUE.VALOR ELSE 0 END)
      - SUM(CASE WHEN BANCOCHEQUE.OPERACAO = 'D' THEN BANCOCHEQUE.VALOR ELSE 0 END) AS "valor"
    FROM (
        SELECT DISTINCT
            CB.CODIGOBAIXA,
            P.NOME,
            P.CODIGOPESSOA,
            PT.CODIGOTIPO,
            CCP.OPERACAO_PLANO_CONTA          AS OPERACAO,
            CCH.*,
            CCH.CODIGOCONTABANCODEPOSITO      AS CODIGOCONTABANCOSUB,
            CNTB.NOME                         AS NOMEBANCO
        FROM CONTA_BAIXA CB
        JOIN CONTA_BAIXA_CONTA_PARCELA CBCP ON CB.CODIGOBAIXA     = CBCP.CODIGOBAIXA
        JOIN CONTA_PARCELA CPAR             ON CPAR.CODIGOPARCELA   = CBCP.CODIGOPARCELA
        JOIN CONTA C                        ON C.CODIGOCONTA        = CPAR.CODIGOCONTA
        JOIN PESSOA P                       ON P.CODIGOPESSOA       = C.CODIGOPESSOA
        JOIN PESSOA_TIPO PT                 ON P.CODIGOTIPO         = PT.CODIGOTIPO
        JOIN CAIXA_CONTA_PLANO CCP          ON C.CODIGOPLANOCONTA   = CCP.CODIGOPLANOCONTA
        JOIN CAIXA CX                       ON C.CODIGOLANCAMENTO   = CX.CODIGOLANCAMENTO
        JOIN CAIXA_ABERTURA CA              ON CX.CODIGOABERTURA    = CA.CODIGOABERTURA
        JOIN CAIXA_CONFIG CXC               ON CA.CODIGOCAIXA       = CXC.CODIGOCAIXA
        LEFT JOIN CONTA_BAIXA_CONTA_CHEQUE CBCCH ON CB.CODIGOBAIXA = CBCCH.CODIGOBAIXA
        LEFT JOIN CONTA_CHEQUE CCH               ON CBCCH.CODIGOCHEQUE = CCH.CODIGOCHEQUE
        JOIN CONTA_BANCO CNTB               ON CCH.CODIGOCONTABANCODEPOSITO = CNTB.CODIGOCONTABANCO
        WHERE PT.CODIGOTIPO <> 2
          AND CCH.DATACOMPENSACAO IS NOT NULL
          AND CNTB.DESATIVADO = 'N'
    ) AS BANCOCHEQUE
    GROUP BY BANCOCHEQUE.NOMEBANCO, BANCOCHEQUE.CODIGOCONTABANCOSUB

) AS TESTE
GROUP BY TESTE.NOMEBANCO, TESTE.CODIGOCONTABANCO
