/* Saldo bancario consolidado: conta corrente + cartao + cheque compensado.
   UNION de 3 sub-queries, agrupado por banco. @EMPRESA parametrizado. */
SELECT
    TESTE.NOMEBANCO    AS "nome",
    'Conta Bancária'   AS "descricao",
    'Saldo disponível' AS "info",
    SUM(TESTE."valor") AS "valor"
FROM (

    /* 1 — Transferencias bancarias diretas */
    SELECT
        BANCO.CODIGOCONTABANCO,
        BANCO.NOMEBANCO,
        SUM(CASE WHEN BANCO.OPERACAO = 'C' THEN BANCO.VALOR ELSE 0 END)
      - SUM(CASE WHEN BANCO.OPERACAO = 'D' THEN BANCO.VALOR ELSE 0 END) AS "valor"
    FROM (
        SELECT DISTINCT
            CB.CODIGOBAIXA,
            CCP.OPERACAO_PLANO_CONTA AS OPERACAO,
            CNTB.NOME                AS NOMEBANCO,
            CBCB.VALOR,
            CNTB.CODIGOCONTABANCO
        FROM CONTA_BAIXA CB
        JOIN CONTA_BAIXA_CONTA_PARCELA CBCP ON CBCP.CODIGOBAIXA    = CB.CODIGOBAIXA
        JOIN CONTA_PARCELA CPAR             ON CPAR.CODIGOPARCELA   = CBCP.CODIGOPARCELA
        JOIN CONTA C                        ON C.CODIGOCONTA        = CPAR.CODIGOCONTA
        JOIN PESSOA P                       ON P.CODIGOPESSOA       = C.CODIGOPESSOA
        JOIN PESSOA_TIPO PT                 ON PT.CODIGOTIPO        = P.CODIGOTIPO
        JOIN CAIXA_CONTA_PLANO CCP          ON CCP.CODIGOPLANOCONTA = C.CODIGOPLANOCONTA
        JOIN CAIXA CX                       ON CX.CODIGOLANCAMENTO  = C.CODIGOLANCAMENTO
        JOIN CAIXA_ABERTURA CA              ON CA.CODIGOABERTURA    = CX.CODIGOABERTURA
        JOIN CAIXA_CONFIG CXC               ON CXC.CODIGOCAIXA      = CA.CODIGOCAIXA
        JOIN CONTA_BAIXA_CONTA_BANCO CBCB   ON CBCB.CODIGOBAIXA     = CB.CODIGOBAIXA
        JOIN CONTA_BANCO CNTB               ON CNTB.CODIGOCONTABANCO = CBCB.CODIGOCONTABANCO
        WHERE CXC.CODIGOEMPRESA = @EMPRESA
          AND CBCB.DATACOMPENSACAO IS NOT NULL
          AND CNTB.DESATIVADO = 'N'
    ) AS BANCO
    GROUP BY BANCO.NOMEBANCO, BANCO.CODIGOCONTABANCO

    UNION ALL

    /* 2 — Cartao de credito/debito compensado */
    SELECT
        BANCOCARTAO.CODIGOCONTABANCOSUB,
        BANCOCARTAO.NOMEBANCO,
        SUM(CASE WHEN BANCOCARTAO.OPERACAO = 'C' THEN BANCOCARTAO.VALOR ELSE 0 END)
      - SUM(CASE WHEN BANCOCARTAO.OPERACAO = 'D' THEN BANCOCARTAO.VALOR ELSE 0 END) AS "valor"
    FROM (
        SELECT DISTINCT
            CB.CODIGOBAIXA,
            CCP.OPERACAO_PLANO_CONTA    AS OPERACAO,
            CNTB.NOME                   AS NOMEBANCO,
            CCAP.CODIGOCONTABANCO       AS CODIGOCONTABANCOSUB,
            CCAP.VALOR
        FROM CONTA_BAIXA CB
        JOIN CONTA_BAIXA_CONTA_PARCELA CBCP ON CBCP.CODIGOBAIXA    = CB.CODIGOBAIXA
        JOIN CONTA_PARCELA CPAR             ON CPAR.CODIGOPARCELA   = CBCP.CODIGOPARCELA
        JOIN CONTA C                        ON C.CODIGOCONTA        = CPAR.CODIGOCONTA
        JOIN PESSOA P                       ON P.CODIGOPESSOA       = C.CODIGOPESSOA
        JOIN PESSOA_TIPO PT                 ON PT.CODIGOTIPO        = P.CODIGOTIPO
        JOIN CAIXA_CONTA_PLANO CCP          ON CCP.CODIGOPLANOCONTA = CPAR.CODIGO_PLANO_CONTA
        JOIN CAIXA CX                       ON CX.CODIGOLANCAMENTO  = C.CODIGOLANCAMENTO
        JOIN CAIXA_ABERTURA CA              ON CA.CODIGOABERTURA    = CX.CODIGOABERTURA
        JOIN CAIXA_CONFIG CXC               ON CXC.CODIGOCAIXA      = CA.CODIGOCAIXA
        JOIN CONTA_BAIXA_CONTA_CARTAO CBCCA ON CBCCA.CODIGOBAIXA    = CB.CODIGOBAIXA
        JOIN CONTA_CARTAO CCA               ON CCA.CODIGOCARTAO     = CBCCA.CODIGOCARTAO
        JOIN CONTA_CARTAO_PARCELA CCAP      ON CCAP.CODIGOCARTAO    = CCA.CODIGOCARTAO
        JOIN CONTA_BANCO CNTB               ON CNTB.CODIGOCONTABANCO = CCAP.CODIGOCONTABANCO
        WHERE CXC.CODIGOEMPRESA = @EMPRESA
          AND CCAP.DATACOMPENSACAO IS NOT NULL
          AND CNTB.DESATIVADO = 'N'
    ) AS BANCOCARTAO
    GROUP BY BANCOCARTAO.NOMEBANCO, BANCOCARTAO.CODIGOCONTABANCOSUB

    UNION ALL

    /* 3 — Cheques compensados */
    SELECT
        BANCOCHEQUE.CODIGOCONTABANCOSUB,
        BANCOCHEQUE.NOMEBANCO,
        SUM(CASE WHEN BANCOCHEQUE.OPERACAO = 'C' THEN BANCOCHEQUE.VALOR ELSE 0 END)
      - SUM(CASE WHEN BANCOCHEQUE.OPERACAO = 'D' THEN BANCOCHEQUE.VALOR ELSE 0 END) AS "valor"
    FROM (
        SELECT DISTINCT
            CB.CODIGOBAIXA,
            CCP.OPERACAO_PLANO_CONTA          AS OPERACAO,
            CNTB.NOME                         AS NOMEBANCO,
            CCH.CODIGOCONTABANCODEPOSITO      AS CODIGOCONTABANCOSUB,
            CCH.VALOR
        FROM CONTA_BAIXA CB
        JOIN CONTA_BAIXA_CONTA_PARCELA CBCP ON CBCP.CODIGOBAIXA    = CB.CODIGOBAIXA
        JOIN CONTA_PARCELA CPAR             ON CPAR.CODIGOPARCELA   = CBCP.CODIGOPARCELA
        JOIN CONTA C                        ON C.CODIGOCONTA        = CPAR.CODIGOCONTA
        JOIN PESSOA P                       ON P.CODIGOPESSOA       = C.CODIGOPESSOA
        JOIN PESSOA_TIPO PT                 ON PT.CODIGOTIPO        = P.CODIGOTIPO
        JOIN CAIXA_CONTA_PLANO CCP          ON CCP.CODIGOPLANOCONTA = C.CODIGOPLANOCONTA
        JOIN CAIXA CX                       ON CX.CODIGOLANCAMENTO  = C.CODIGOLANCAMENTO
        JOIN CAIXA_ABERTURA CA              ON CA.CODIGOABERTURA    = CX.CODIGOABERTURA
        JOIN CAIXA_CONFIG CXC               ON CXC.CODIGOCAIXA      = CA.CODIGOCAIXA
        LEFT JOIN CONTA_BAIXA_CONTA_CHEQUE CBCCH ON CBCCH.CODIGOBAIXA = CB.CODIGOBAIXA
        LEFT JOIN CONTA_CHEQUE CCH               ON CCH.CODIGOCHEQUE  = CBCCH.CODIGOCHEQUE
        JOIN CONTA_BANCO CNTB               ON CNTB.CODIGOCONTABANCO = CCH.CODIGOCONTABANCODEPOSITO
        WHERE PT.CODIGOTIPO <> 2
          AND CXC.CODIGOEMPRESA = @EMPRESA
          AND CCH.DATACOMPENSACAO IS NOT NULL
          AND CNTB.DESATIVADO = 'N'
    ) AS BANCOCHEQUE
    GROUP BY BANCOCHEQUE.NOMEBANCO, BANCOCHEQUE.CODIGOCONTABANCOSUB

) AS TESTE
GROUP BY TESTE.NOMEBANCO, TESTE.CODIGOCONTABANCO
