/* Saldo atual dos caixas abertos (dinheiro em especie). Um total por caixa.
   CF.CODIGOABERTURA IS NULL = caixas que ainda nao foram fechados (saldo vivo). */
SELECT
    CXC.NOME           AS "nome",
    'Caixa (Dinheiro)' AS "descricao",
    'Saldo disponível' AS "info",
    SUM(CASE WHEN CC.OPERACAO_PLANO_CONTA = 'C' THEN CP.TOTAL ELSE 0 END)
  - SUM(CASE WHEN CC.OPERACAO_PLANO_CONTA = 'D' THEN CP.TOTAL ELSE 0 END) AS "valor",
    'ion-cash'         AS "icon"
FROM CAIXA CX
JOIN CAIXA_ABERTURA CA              ON CA.CODIGOABERTURA   = CX.CODIGOABERTURA
JOIN CAIXA_CONFIG CXC               ON CXC.CODIGOCAIXA     = CA.CODIGOCAIXA
JOIN CONTA_BAIXA CB                 ON CB.CODIGOLANCAMENTO  = CX.CODIGOLANCAMENTO
JOIN CONTA_BAIXA_CONTA_PARCELA CBCP ON CBCP.CODIGOBAIXA    = CB.CODIGOBAIXA
JOIN CONTA_PARCELA CP               ON CP.CODIGOPARCELA     = CBCP.CODIGOPARCELA
JOIN CAIXA_CONTA_PLANO CC           ON CC.CODIGOPLANOCONTA  = CP.CODIGO_PLANO_CONTA
LEFT JOIN FORMA_PAGAMENTO_CONDICAO FPC ON FPC.CODIGO_FORMA_PAGAMENTO_CONDICAO = CP.CODIGO_FORMA_PAGAMENTO_CONDICAO
LEFT JOIN CONDICAO_PAGAMENTO CPA    ON CPA.CODIGO_CONDICAO_PAGAMENTO = FPC.CODIGO_CONDICAO_PAGAMENTO
LEFT JOIN FORMA_PAGAMENTO FP        ON FP.CODIGO_FORMA_PAGAMENTO     = FPC.CODIGO_FORMA_PAGAMENTO
LEFT JOIN CAIXA_FECHAMENTO CF       ON CF.CODIGOABERTURA   = CA.CODIGOABERTURA
WHERE UPPER(CP.SITUACAO) = 'LIQUIDADA'
  AND (FP.CODIGO_MEIO_PAGAMENTO_FISCAL NOT IN (15, 18) OR FP.CODIGO_MEIO_PAGAMENTO_FISCAL IS NULL)
  AND (FP.DESCRICAO IS NULL OR FP.CHEQUE_PROPRIO = 'N')
  AND (CPA.MOVIMENTA_CAIXA = 'S' OR CPA.MOVIMENTA_CAIXA IS NULL)
  AND (CC.PLANOCONTA <> 'Saque bancário' OR CC.OPERACAO_PLANO_CONTA = 'C')
  AND (CC.PLANOCONTA <> 'Depósito bancário' OR CC.OPERACAO_PLANO_CONTA = 'D')
  AND CF.CODIGOABERTURA IS NULL
  AND CC.PLANOCONTA <> 'Haver'
  AND CXC.CODIGOEMPRESA = @EMPRESA
GROUP BY CXC.NOME
